language: java
sudo: false

cache:
  directories:
    - "$HOME/.m2"

jobs:
  include:
    # 1.1 Check JDK
    - stage: test
      jdk: openjdk12
      script: mvn clean
      name: "Check"

    # 1.2 Compile project.
    - stage: test
      jdk: oraclejdk12
      env: JAVADOC=true
      script:
        - mvn clean compile
      name: "Java Application Compile"

branches:
  only:
    - master

notifications:
  slack: easytestit:CjqjZLdZMpVFzJEDK8ItU4C0