language: java
sudo: false

cache:
  directories:
    - "$HOME/.m2"

jobs:
  include:
    # 1.1 Check JDK
    - stage: test
      jdk: openjdk12
      script: mvn clean
      name: "Check"

    # 1.2 Check javadoc. We need to use this version to properly detect errors.
    - stage: test
      jdk: oraclejdk12
      env: JAVADOC=true
      script:
        - mvn clean verify -DskipTests=true
        - mvn javadoc:aggregate
      name: "Java Doc Creating"

branches:
  only:
    - master

notifications:
  slack: easytestit:CjqjZLdZMpVFzJEDK8ItU4C0